Chore/RB-33 Implement audit changes to Dockerfile
appliedblockchain/algorand-randomness-beacon pull request #40
Opened 2022-09-08 15:03 UTC by NilsonBertolaAB

# Description
Implement audit changes to Dockerfile
- Fix installed packages versions
- Remove cache after isntalation

# Task
[RB-33](https://appliedblockchain.atlassian.net/browse/RB-33)

2022-09-08 15:46 UTC, campbell-codes requested changes
If we need the rm then it's good I'm happy to approve just not sure we do

2022-09-08 15:46 UTC, campbell-codes commented on services/app/Dockerfile
> +RUN rm -rf /var/cache/apk/*
Is this needed if cache is disabled anyway?

2022-09-08 15:46 UTC, campbell-codes commented on services/vrf/Dockerfile
> +RUN rm -rf /var/cache/apk/*
Same

2022-09-08 15:46 UTC, campbell-codes commented on services/vrf/Dockerfile
> +RUN rm -rf /var/cache/apk/*
Same

2022-09-08 20:21 UTC, seromenho approved these changes
Good stuff 👌

2022-09-13 08:36 UTC, campbell-codes approved these changes
Looks good

2022-09-13 08:36 UTC, merged